global using RouletteConsoleApp.Models;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using RouletteConsoleApp.Interfaces;
global using RouletteConsoleApp.Services;
global using Microsoft.Extensions.DependencyInjection;